
language: c
#######################################################################################
os:
  - linux
  
addons:
  apt:
    packages:
      - curl

#######################################################################################


before_install:

  - sudo apt-get update -qq
  
  - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8 ~/arm-eabi-4.8/
  
  - sudo chmod -R a+x *

#######################################################################################


script:  
  - export ARCH=arm
  - export ARCH_MTK_PLATFORM=mt6572
  - export CROSS_COMPILE=~/arm-eabi-4.8/bin/arm-eabi-
  #- export KBUILD_BUILD_USER="root"
  #- export KBUILD_BUILD_HOST="Manish4586"
  #- KERNEL_DIR=$PWD/android_kernel_alcatel_pop_c3
  #- ZIMAGE=$KERNEL_DIR/arch/arm/boot/zImage
  #- mkdir -p out
  #- make O=out clean
  #- make O=out mrproper
  #- make O=out pop_c3_defconfig 
  #- make O=out -j4 
  - export KBUILD_BUILD_USER="fujitsu"
  - export KBUILD_BUILD_HOST="ALGPHELLO"
  - KERNEL_DIR=$PWD/android_kernel_alcatel_pop_c3
  - ZIMAGE=$KERNEL_DIR/arch/arm/boot/zImage
  - mkdir /home/travis/build/ALGPHELLO/android_kernel_alcatel_pop_c3/tools/tools
  - make pop_c3_defconfig  
  - bash build.sh
  - make -j16
  #- make ARCH=arm -j4 clean mrproper

after_success:
  - curl --upload-file arch/arm/boot/zImage https://transfer.sh/pop_c3_kernel
  
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_TB"
  
  on:
    tags: false
    repo: AOGP/android_kernel_alcatel_pop_c3
    branch: master
branches:
  except:
    - /^(?i:untagged)-.*$/
  
  
