
language: c
#######################################################################################
os:
  - linux
  
addons:
  apt:
    packages:
      - curl

#######################################################################################


before_install:

  - sudo apt-get update -qq
  
  - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8 ~/arm-eabi-4.8/

#######################################################################################


script:  
  - export ARCH=arm
  - export ARCH_MTK_PLATFORM=mt6572
  - export CROSS_COMPILE=~/arm-eabi-4.8/bin/arm-eabi-
  - export KBUILD_BUILD_USER="root"
  - export KBUILD_BUILD_HOST="Manish4586"
  - KERNEL_DIR=$PWD
  - ZIMAGE=$KERNEL_DIR/arch/arm/boot/zImage
  - make pop_c3_defconfig 
  - make -j4 
  - make ARCH=arm -j4 clean mrproper

after_success:
  - curl --upload-file arch/arm/boot/zImage https://transfer.sh/oreo_c3_kernel
  
  
